version: '3'
services:
  frontend:
    build:
      context: ./client  # Assumendo che il Dockerfile sia nella cartella client
    ports:
      - "80:3000"  # La porta 80 pubblica è mappata alla porta 80 di NGINX
    depends_on:
      - backend
    networks:
      - embedai-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - embedai-network

networks:
  embedai-network:
    driver: bridge
